# 开发环境配置
server:
  port: 8088

# 头像上传配置
avatar:
  base:
    url: http://127.0.0.1:8088/avatars/

# 图片上传配置
image:
  base:
    url: http://127.0.0.1:8088/images/

# 服务基础URL配置
service:
  base:
    url: http://127.0.0.1:8088/